from sanitizer import strip_metadata
import streamlit as st
from PIL import Image, ExifTags
import base64
from io import BytesIO
import numpy as np
import datetime
import os
from phash import (
    image_phash,
    load_known_hashes,
    save_known_hashes,
    hamming_distance,
    video_phash,
    video_hamming_distance,
    load_known_video_hashes,
    save_known_video_hashes,
)
from db import init_db, insert_video_hashes, list_videos, get_video_hashes, delete_video
from steg import encode_image_with_message, decode_message_from_image, image_to_bytes

# PDF generation
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    has_pdf = True
except ImportError:
    has_pdf = False


# helper to pull human-readable EXIF data

def extract_exif_dict(image: Image.Image) -> dict:
    """Return a simple mapping of EXIF tag names to values.

    Uses :meth:`PIL.Image.Image.getexif` which is the modern API.  Some
    images (or blank canvases) may not support EXIF at all, so we catch
    ``AttributeError`` and just return an empty dict.
    """
    try:
        raw = image.getexif()
    except AttributeError:
        return {}
    if not raw:
        return {}
    exif_data = {}
    for tag, value in dict(raw).items():
        decoded = ExifTags.TAGS.get(tag, tag)
        exif_data[decoded] = value
    return exif_data


def format_gps_info(gps_info: dict) -> str:
    # gps_info is a dictionary with numeric keys corresponding to GPS tags
    # we will just stringify it for now
    try:
        # convert rational tuples to floats for readability
        def _convert(coord):
            return tuple(float(x[0]) / float(x[1]) if isinstance(x, tuple) else x for x in coord)
        entries = []
        for k, v in gps_info.items():
            name = ExifTags.GPSTAGS.get(k, k)
            entries.append(f"{name}: {_convert(v)}")
        return "; ".join(entries)
    except Exception:
        return str(gps_info)


def apply_anti_ai_shield(image: Image.Image, intensity: int = 1) -> Image.Image:
    arr = np.array(image).astype(np.int16)
    noise = np.random.randint(-intensity, intensity + 1, arr.shape, dtype=np.int16)
    arr = arr + noise
    arr = np.clip(arr, 0, 255).astype(np.uint8)
    return Image.fromarray(arr)



# Encode / Decode helpers (use steg.py for robustness)
def encode_message(message, image):
    try:
        encoded = encode_image_with_message(image, message)
        encoded_path = "encoded.png"
        encoded.save(encoded_path)
        st.success("Image encoded successfully.")
        show_encoded_image(encoded_path)
        return encoded_path
    except Exception as e:
        st.error(f"Failed to encode image: {e}")
        return None

def decode_message(image):
    try:
        decoded_message = decode_message_from_image(image)
        if not decoded_message:
            col = st.container()
            col.warning("No hidden message found (or message corrupted).")
        else:
            st.success("Hidden message recovered:")
            st.markdown(f"**{decoded_message}**")

        # Show the decoded image preview
        st.image(image, caption="Decoded Image", use_container_width=True)

        # Persist the last decoded message for report generation
        st.session_state["last_decoded_message"] = decoded_message

        if st.button("Generate Official Cyber-Cell Report"):
            today = datetime.date.today()
            dm = st.session_state.get("last_decoded_message", "")
            if has_pdf:
                pdf_buffer = BytesIO()
                c = canvas.Canvas(pdf_buffer, pagesize=letter)
                text = c.beginText(40, 750)
                text.setFont("Helvetica", 12)
                text.textLine("Cyber Crime Complaint")
                text.textLine(f"Date: {today}")
                text.textLine("")
                text.textLines(f"Decoded secret message: {dm}")
                text.textLine("")
                text.textLines("The undersigned victim hereby reports the above information to the Cyber Crime Cell for investigation. All data contained herein is true to the best of my knowledge. Please treat this as a formal complaint.")
                text.textLine("")
                text.textLine("(This report was auto-generated by AuraGuard - Digital Safety & Privacy)")
                c.drawText(text)
                c.showPage()
                c.save()
                pdf_buffer.seek(0)
                st.download_button("Download Report as PDF", data=pdf_buffer, file_name="cyber_cell_report.pdf", mime="application/pdf")
            else:
                report = (
                    f"Cyber Crime Complaint\nDate: {today}\n\n"
                    f"Decoded secret message: {dm}\n\n"
                    "The undersigned victim hereby reports the above information to the Cyber Crime Cell for investigation. All data contained herein is true to the best of my knowledge. Please treat this as a formal complaint.\n\n"
                    "(This report was auto-generated by AuraGuard - Digital Safety & Privacy)\n"
                )
                st.download_button("Download Report", data=report, file_name="cyber_cell_report.txt", mime="text/plain")
    except Exception as e:
        st.error(f"Failed to decode image: {e}")


# Function to display the encoded image in the UI and add a download button
def show_encoded_image(image_path):
    encoded_image = Image.open(image_path)

    st.image(encoded_image, caption="Encoded Image", use_container_width=True)

    buffered = BytesIO()
    encoded_image.save(buffered, format="PNG")

    img_str = base64.b64encode(buffered.getvalue()).decode()

    href = ('<a href="data:file/png;base64,' + img_str + '" '
            'download="' + image_path + '">Download Encoded Image</a>')

    st.markdown(href, unsafe_allow_html=True)


# Streamlit GUI setup
st.set_page_config(
    page_title="🛡️ AuraGuard | Digital Safety Platform",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@300;500;700&display=swap');

* { font-family: 'Rajdhani', sans-serif; }
h1, h2, h3 { font-family: 'Orbitron', monospace; }

.stApp {
    background: linear-gradient(135deg, #000000 0%, #1a0033 25%, #330066 50%, #6600cc 75%, #9933ff 100%);
    animation: bgShift 25s ease infinite;
    background-size: 400% 400%;
}

@keyframes bgShift {
    0%, 100% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
}

.main .block-container {
    padding: 3rem;
    background: rgba(0, 0, 0, 0.7);
    border-radius: 30px;
    border: 2px solid rgba(153, 51, 255, 0.5);
    box-shadow: 0 0 100px rgba(153, 51, 255, 0.4), inset 0 0 50px rgba(153, 51, 255, 0.1);
    backdrop-filter: blur(20px);
}

h1 {
    background: linear-gradient(90deg, #ff00ff, #00ffff, #ff00ff);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size: 4rem !important;
    text-align: center;
    animation: neonGlow 2s ease-in-out infinite, textShift 3s linear infinite;
    text-shadow: 0 0 20px rgba(255, 0, 255, 0.8);
    letter-spacing: 5px;
}

@keyframes neonGlow {
    0%, 100% { filter: drop-shadow(0 0 20px #ff00ff) drop-shadow(0 0 40px #00ffff); }
    50% { filter: drop-shadow(0 0 40px #00ffff) drop-shadow(0 0 60px #ff00ff); }
}

@keyframes textShift {
    0% { background-position: 0% 50%; }
    100% { background-position: 200% 50%; }
}

.stTabs [data-baseweb="tab-list"] {
    gap: 20px;
    background: rgba(0, 0, 0, 0.5);
    padding: 20px;
    border-radius: 20px;
    border: 2px solid rgba(153, 51, 255, 0.3);
}

.stTabs [data-baseweb="tab"] {
    height: 70px;
    background: linear-gradient(135deg, rgba(102, 0, 204, 0.3), rgba(153, 51, 255, 0.3));
    border-radius: 15px;
    color: #ffffff;
    font-weight: 700;
    font-size: 1.2rem;
    border: 2px solid rgba(153, 51, 255, 0.5);
    transition: all 0.4s;
    text-transform: uppercase;
    letter-spacing: 2px;
}

.stTabs [data-baseweb="tab"]:hover {
    transform: translateY(-5px) scale(1.05);
    box-shadow: 0 10px 40px rgba(153, 51, 255, 0.6);
    border-color: #ff00ff;
}

.stTabs [aria-selected="true"] {
    background: linear-gradient(135deg, #6600cc, #9933ff);
    box-shadow: 0 0 30px rgba(153, 51, 255, 0.8), inset 0 0 20px rgba(255, 0, 255, 0.3);
    transform: translateY(-5px) scale(1.08);
}

.stButton>button {
    background: linear-gradient(135deg, #ff00ff, #00ffff);
    color: #000;
    border: none;
    border-radius: 15px;
    padding: 1rem 3rem;
    font-weight: 900;
    font-size: 1.1rem;
    text-transform: uppercase;
    letter-spacing: 3px;
    box-shadow: 0 0 30px rgba(255, 0, 255, 0.6);
    transition: all 0.3s;
}

.stButton>button:hover {
    transform: scale(1.1) translateY(-3px);
    box-shadow: 0 0 50px rgba(0, 255, 255, 0.8);
    background: linear-gradient(135deg, #00ffff, #ff00ff);
}

.stTextInput>div>div>input, .stTextArea>div>div>textarea {
    background: rgba(0, 0, 0, 0.6);
    border: 2px solid rgba(153, 51, 255, 0.5);
    border-radius: 10px;
    color: #ffffff;
    font-size: 1.1rem;
}

.stTextInput>div>div>input:focus, .stTextArea>div>div>textarea:focus {
    border-color: #ff00ff;
    box-shadow: 0 0 20px rgba(255, 0, 255, 0.5);
}

[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #000000, #1a0033, #330066);
    border-right: 2px solid rgba(153, 51, 255, 0.5);
}

[data-testid="stSidebar"] * { color: #ffffff !important; }

[data-testid="stImage"] {
    border-radius: 20px;
    border: 3px solid rgba(153, 51, 255, 0.5);
    box-shadow: 0 0 30px rgba(153, 51, 255, 0.4);
    transition: all 0.3s;
}

[data-testid="stImage"]:hover {
    transform: scale(1.05);
    box-shadow: 0 0 50px rgba(255, 0, 255, 0.6);
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div style='text-align: center; margin-bottom: 3rem;'>
    <h1>🛡️ AURAGUARD</h1>
    <p style='color: #00ffff; font-size: 1.5rem; font-weight: 700; letter-spacing: 3px; text-shadow: 0 0 10px #00ffff;'>DIGITAL SAFETY PLATFORM</p>
    <p style='color: #ff00ff; font-size: 1.2rem; letter-spacing: 2px;'>BY TECHSHE4</p>
</div>
""", unsafe_allow_html=True)

# path to store known/banned perceptual hashes
KNOWN_HASHES_PATH = "known_hashes.json"
# separate file for video perceptual hashes
KNOWN_VIDEO_HASHES_PATH = "known_video_hashes.json"


# --- UI Tabs: Encode | Decode | Image Analysis | Video Analysis | Moderation ----------------------------------
tabs = st.tabs(["🔐 ENCODE", "🔓 DECODE", "🖼️ IMAGE ANALYSIS", "📹 VIDEO ANALYSIS", "⚖️ MODERATION"])

encode_tab = tabs[0]
decode_tab = tabs[1]
image_tab = tabs[2]
video_tab = tabs[3]
moderation_tab = tabs[4]


def show_banned_image_list():
    known = load_known_hashes(KNOWN_HASHES_PATH)
    if not known:
        st.info("✅ No banned image hashes yet. Platform is clean.")
        return
    st.markdown(f"### 🚫 **{len(known)} Banned Image Hash** {'(es)' if len(known) != 1 else ''}")
    for i, h in enumerate(known):
        with st.container():
            cols = st.columns([0.5, 5, 1])
            cols[0].write(f"**#{i+1}**")
            cols[1].code(h, language="text")
            if cols[2].button("❌", key=f"remove_img_{i}", help="Remove this hash"):
                known.pop(i)
                save_known_hashes(KNOWN_HASHES_PATH, known)
                st.experimental_rerun()


def show_banned_video_list():
    known_vids = load_known_video_hashes(KNOWN_VIDEO_HASHES_PATH)
    if not known_vids:
        st.info("No banned video entries stored.")
        return
    st.write(f"{len(known_vids)} banned videos:")
    for i, entry in enumerate(known_vids):
        cols = st.columns([6, 1])
        # show first 6 hashes as summary
        summary = ', '.join(entry[:6])
        cols[0].write(f"Entry #{i}: {summary}... (total frames: {len(entry)})")
        if cols[1].button("Remove", key=f"remove_vid_{i}"):
            known_vids.pop(i)
            save_known_video_hashes(KNOWN_VIDEO_HASHES_PATH, known_vids)
            st.experimental_rerun()


with encode_tab:
    st.header("Encode Image")
    st.caption("Sanitize metadata, optionally add anti-morphing noise, then encode message.")
    msg = st.text_input("Message to hide", key="enc_msg")
    img_file = st.file_uploader("Choose image to encode", type=["png", "jpg", "jpeg"], key="enc_img")
    shield = st.checkbox("Enable Anti-Morphing Shield (invisible noise)", key="enc_shield")

    if img_file and msg:
        img = Image.open(img_file)
        st.subheader("Sanitization & Preview")
        exif = extract_exif_dict(img)
        if exif:
            st.markdown("**EXIF metadata before sanitization:**")
            st.json(exif)
        clean = strip_metadata(img_file)
        st.image(clean, caption="Sanitized image")
        if shield:
            clean = apply_anti_ai_shield(clean, intensity=1)
            st.info("Anti-Morphing Shield applied.")

        if st.button("Encode and Download"):
            encoded_path = encode_message(msg, clean)
            # immediately verify by decoding the just-created encoded image
            if encoded_path:
                try:
                    enc_img = Image.open(encoded_path)
                    decode_message(enc_img)
                except Exception as e:
                    st.warning(f"Could not open encoded image for verification: {e}")

# initialise sqlite DB for video hashes
db_conn = init_db()


with decode_tab:
    st.header("Decode Image / Analyze Media")
    st.subheader("Image decoding")
    dec_img = st.file_uploader("Upload encoded image to decode", type=["png", "jpg", "jpeg"], key="dec_img")
    if dec_img:
        img = Image.open(dec_img)
        decode_message(img)

    # Quick verification button to decode the last encoded image produced by this app
    if st.button("Verify last encoded image", key="verify_last_encoded"):
        encoded_path = "encoded.png"
        if os.path.exists(encoded_path):
            try:
                enc = Image.open(encoded_path)
                st.info("Found encoded.png — running verification decode...")
                decode_message(enc)
            except Exception as e:
                st.error(f"Failed to open or decode encoded.png: {e}")
        else:
            st.warning("No encoded image found at 'encoded.png'. Please encode an image first.")


with image_tab:
    with st.container():
        st.header("🖼️ Image Analysis")
        st.caption("Compare two images via perceptual hash (pHash) to detect similarity.")

    # --- Image comparison section ---
    st.markdown("**Compare two images** — compute perceptual hashes for each image and report the Hamming distance.")
    img_comp_mode = st.radio("Image compare mode", ["Upload both images", "Compare with banned list"], key="img_comp_mode")
    img_comp_thresh = st.slider("Image similarity threshold (max Hamming distance)", 0, 64, 10, key="img_comp_thresh")
    
    if img_comp_mode == "Upload both images":
        col_img_a, col_img_b = st.columns(2)
        img_a = col_img_a.file_uploader("Upload Original Image", type=["png", "jpg", "jpeg"], key="comp_img_a")
        img_b = col_img_b.file_uploader("Upload Edited/Compared Image", type=["png", "jpg", "jpeg"], key="comp_img_b")
        
        if img_a and img_b and st.button("Compare uploaded images", key="compare_images_btn"):
            try:
                orig_img = Image.open(img_a)
                edit_img = Image.open(img_b)
                
                # compute pHashes
                hash_a = image_phash(orig_img)
                hash_b = image_phash(edit_img)
                
                st.write(f"**Original image pHash:** `{hash_a}`")
                st.write(f"**Edited image pHash:** `{hash_b}`")
                
                # compute distance
                dist = hamming_distance(hash_a, hash_b)
                st.write(f"**Hamming distance:** `{dist}`")
                
                if dist <= img_comp_thresh:
                    st.success(f"✅ Images are SIMILAR (distance {dist} ≤ threshold {img_comp_thresh}).")
                else:
                    st.info(f"❌ Images are NOT similar (distance {dist} > threshold {img_comp_thresh}).")
                
                # show thumbnails side-by-side
                col_thumb_a, col_thumb_b = st.columns(2)
                col_thumb_a.image(orig_img, caption="Original", use_container_width=True)
                col_thumb_b.image(edit_img, caption="Edited", use_container_width=True)
            except Exception as e:
                st.warning(f"Could not compare images: {e}")
    
    else:  # Compare with banned list
        st.markdown("**Compare with banned image hashes**")
        img_upload = st.file_uploader("Upload image to check against bans", type=["png", "jpg", "jpeg"], key="img_ban_check")
        
        if img_upload and st.button("Check against banned images", key="check_img_bans_btn"):
            try:
                img = Image.open(img_upload)
                img_hash = image_phash(img)
                st.write(f"**Uploaded image pHash:** `{img_hash}`")
                
                known = load_known_hashes("known_hashes.json")
                if not known:
                    st.info("✅ No banned image hashes in database.")
                else:
                    st.write(f"Comparing against {len(known)} banned images...")
                    found = []
                    for i, banned_hash in enumerate(known):
                        d = hamming_distance(img_hash, banned_hash)
                        if d <= img_comp_thresh:
                            found.append((i, d))
                    
                    if found:
                        st.error(f"⚠️ **MATCH FOUND:** Image is similar to {len(found)} banned image(s):")
                        for idx, d in found:
                            st.write(f"- Banned image #{idx+1}: distance `{d}`")
                    else:
                        st.success(f"✅ No matches found (all distances > {img_comp_thresh}).")
            except Exception as e:
                st.warning(f"Could not check image: {e}")


with video_tab:
    with st.container():
        st.header("📹 Video Analysis")
        st.caption("Compare two videos or check a single video against stored banned videos.")

    # --- two-video comparison -------------------------------------------------
    st.markdown("**Compare two videos** — compute sampled frame pHashes for each video and report the minimum Hamming distance.")
    comp_mode = st.radio("Compare mode", ["Upload both videos", "Compare with DB entry"], key="comp_mode")
    comp_thresh = st.slider("Similarity threshold (max Hamming distance)", 0, 64, 10, key="comp_thresh")
    
    if comp_mode == "Upload both videos":
        col_a, col_b = st.columns(2)
        vid_a = col_a.file_uploader("Upload Original Video", type=["mp4", "mov", "avi", "mkv"], key="comp_vid_a")
        vid_b = col_b.file_uploader("Upload Edited Video", type=["mp4", "mov", "avi", "mkv"], key="comp_vid_b")
        if vid_a and vid_b and st.button("Compare uploaded videos", key="compare_videos_btn"):
            import tempfile, os
            suffix_a = os.path.splitext(vid_a.name)[1] or ".mp4"
            suffix_b = os.path.splitext(vid_b.name)[1] or ".mp4"
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix_a) as ta:
                ta.write(vid_a.read())
                path_a = ta.name
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix_b) as tb:
                tb.write(vid_b.read())
                path_b = tb.name
            try:
                hashes_a = video_phash(path_a)
                hashes_b = video_phash(path_b)
                st.write(f"Computed {len(hashes_a)} hashes for video A and {len(hashes_b)} for video B.")
                best = video_hamming_distance(hashes_a, hashes_b)
                st.write(f"Minimum Hamming distance between any sampled frames: **{best}**")
                if best <= comp_thresh:
                    st.success(f"Videos are similar (distance {best} <= threshold {comp_thresh}).")
                else:
                    st.info(f"Videos are NOT similar (distance {best} > threshold {comp_thresh}).")

                # show small matrix of pairwise distances (limited size)
                max_display = 10
                na = min(len(hashes_a), max_display)
                nb = min(len(hashes_b), max_display)
                st.markdown("**Sampled frame hash matrix (showing up to 10x10)**")
                table = []
                header = [""] + [f"B#{i}" for i in range(nb)]
                table.append(header)
                for i in range(na):
                    row = [f"A#{i}"]
                    for j in range(nb):
                        d = hamming_distance(hashes_a[i], hashes_b[j])
                        row.append(str(d))
                    table.append(row)
                # render simple markdown table
                md = "\n".join(["|" + "|".join(r) + "|" for r in table])
                sep = "|" + "|".join(["---"] * len(table[0])) + "|\n"
                st.markdown(md.replace(table[0][0], table[0][0]) + "\n" + sep, unsafe_allow_html=True)
            except Exception as e:
                st.warning(f"Could not compute video hashes: {e}")
    
    else:  # Compare with DB entry
        st.markdown("**Compare with a stored DB entry**")
        try:
            db_list = list_videos(db_conn)
            if not db_list:
                st.warning("No videos in database yet. Please ban a video first.")
            else:
                # create selectbox with db entries
                db_options = {f"ID {e['id']} — {e['name']}": e['id'] for e in db_list}
                selected = st.selectbox("Select a stored DB video", list(db_options.keys()), key="comp_db_select")
                db_video_id = db_options[selected]
                
                vid_upload = st.file_uploader("Upload video to compare against DB entry", type=["mp4", "mov", "avi", "mkv"], key="comp_vid_upload_db")
                
                if vid_upload and st.button("Compare with DB entry", key="compare_db_btn"):
                    import tempfile, os
                    suffix = os.path.splitext(vid_upload.name)[1] or ".mp4"
                    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                        tmp.write(vid_upload.read())
                        path_upload = tmp.name
                    try:
                        # get hashes from DB
                        hashes_db = get_video_hashes(db_conn, db_video_id)
                        # compute hashes for uploaded video
                        hashes_upload = video_phash(path_upload)
                        
                        st.write(f"DB video has {len(hashes_db)} frame hashes; uploaded video has {len(hashes_upload)}.")
                        best = video_hamming_distance(hashes_upload, hashes_db)
                        st.write(f"Minimum Hamming distance: **{best}**")
                        if best <= comp_thresh:
                            st.success(f"Videos are SIMILAR (distance {best} <= threshold {comp_thresh}).")
                        else:
                            st.info(f"Videos are NOT similar (distance {best} > threshold {comp_thresh}).")

                        # show small matrix
                        max_display = 10
                        na = min(len(hashes_upload), max_display)
                        nb = min(len(hashes_db), max_display)
                        st.markdown("**Sampled frame hash matrix (showing up to 10x10)**")
                        table = []
                        header = [""] + [f"DB#{i}" for i in range(nb)]
                        table.append(header)
                        for i in range(na):
                            row = [f"UP#{i}"]
                            for j in range(nb):
                                d = hamming_distance(hashes_upload[i], hashes_db[j])
                                row.append(str(d))
                            table.append(row)
                        md = "\n".join(["|" + "|".join(r) + "|" for r in table])
                        sep = "|" + "|".join(["---"] * len(table[0])) + "|\n"
                        st.markdown(md.replace(table[0][0], table[0][0]) + "\n" + sep, unsafe_allow_html=True)
                    except Exception as e:
                        st.warning(f"Could not compare: {e}")
        except Exception as e:
            st.warning(f"Could not load DB videos: {e}")    # --- existing single-video analysis (optional) ---------------------------
    st.markdown("---")
    st.subheader("Single video analysis")
    if st.checkbox("Show single-video analysis against stored bans", key="show_single_vid_analysis"):
        video_file = st.file_uploader("Upload video for similarity check", type=["mp4", "mov", "avi", "mkv"], key="dec_video")
        default_thresh = st.slider("Default similarity threshold (Hamming distance)", 0, 64, 10, key="global_thresh")
        if video_file:
            import tempfile, os
            suffix = os.path.splitext(video_file.name)[1] or ".mp4"
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                tmp.write(video_file.read())
                video_path = tmp.name
            try:
                hashes = video_phash(video_path)
                st.write(f"Computed {len(hashes)} frame hashes for video.")
                thresh = st.slider("Max Hamming distance for similarity", 0, 64, default_thresh, key="video_thresh_local")
                known_vids = load_known_video_hashes(KNOWN_VIDEO_HASHES_PATH)
                found = []
                for idx, khashes in enumerate(known_vids):
                    try:
                        d = video_hamming_distance(hashes, khashes)
                        if d <= thresh:
                            found.append((idx, d))
                    except Exception:
                        continue
                if found:
                    st.error("⚠️ This video is similar to stored banned videos:")
                    for idx, d in found:
                        st.write(f"- entry #{idx} distance {d}")
                else:
                    st.success("No similar banned video found.")
                if st.button("Ban this video (store hashes)", key="ban_video_tab"):
                    # store to the existing JSON file for compatibility
                    known_vids.append(hashes)
                    save_known_video_hashes(KNOWN_VIDEO_HASHES_PATH, known_vids)
                    # also store into the sqlite DB with a helpful name and metadata
                    try:
                        vid_id = insert_video_hashes(db_conn, video_file.name, hashes, meta={"source": "uploaded_from_UI"})
                        st.success(f"Video hashes added to banned list (db id={vid_id}).")
                    except Exception as e:
                        st.warning(f"Saved to JSON but failed to insert to DB: {e}")
            except Exception as e:
                st.warning(f"Could not process video: {e}")

with moderation_tab:
    st.header("Moderation — Banned Hashes")
    st.subheader("Image hashes")
    show_banned_image_list()
    st.markdown("---")
    st.subheader("Video hashes")
    show_banned_video_list()
    st.markdown("---")
    st.subheader("Database stored videos")
    try:
        db_list = list_videos(db_conn)
        if not db_list:
            st.info("No videos stored in DB.")
        else:
            for entry in db_list:
                cols = st.columns([4, 1, 1])
                cols[0].write(f"ID {entry['id']} — {entry['name']} ({entry['created_at']})")
                if cols[1].button("Compare", key=f"compare_db_{entry['id']}"):
                    # load hashes and compare with a user-uploaded file
                    st.info("Select a video to compare against this DB entry using the 'Compare two videos' section.")
                if cols[2].button("Delete", key=f"del_db_{entry['id']}"):
                    delete_video(db_conn, entry['id'])
                    st.experimental_rerun()
    except Exception as e:
        st.warning(f"Could not list DB videos: {e}")
    st.markdown("---")
    if st.button("Clear all banned image hashes"):
        save_known_hashes(KNOWN_HASHES_PATH, [])
        st.experimental_rerun()
    if st.button("Clear all banned video hashes"):
        save_known_video_hashes(KNOWN_VIDEO_HASHES_PATH, [])
        st.experimental_rerun()
